### PR TITLE
Update Dockerfile with .py endpoint

### PR DESCRIPTION
**Pull request by georgyo**
Make the docker entrypoint run.py

Fix `run-tests-in-docker.sh` to match how tests are run on production.
    
Fix sanitation of output
    
Make json output human readable for better results diffing.

### CODE REVIEW

**Comment by georgyo** [comment]
I have now tested this runner against all existing problems to verify that it should not break when deployed. See https://github.com/exercism/ocaml/pull/457

**Review by ErikSchierboom — APPROVED** [review]
LGTM

**Review by iHiD — CHANGES_REQUESTED** [review]
Our infrastructure executes `run.sh`. It does not honour the `ENTRYPOINT` in the dockerfile. 

Therefore my understanding is that the entrypoint should always be `run.sh` to ensure that local execution matches remote execution.

**Comment by ErikSchierboom** [comment]
I likely misremembered then. Should be as easy as creating a `run.sh` file, having that as the ENTRYPOINT and calling the Python file from it.
I can double check tomorrow.

**Comment by georgyo** [comment]
Ah good to know about `run.sh` added a wrapper script to that effect.

**Review by iHiD — APPROVED** [review]

**Comment by ErikSchierboom** [comment]
Thanks!

**Pull request merged**
