### PR TITLE
Update test runner to version 2

### PR DESCRIPTION
**Pull request by georgyo**
Upgrading `results.json` to spec v2 is pretty difficult for ocaml, since the test output likes to hide itself. Luckily every single project in exercise is using `ounit2` and we can have that output a junit results file. 

That file is unfortunately XML, and parsing that in bash would have been very difficult, so this commit also rewrites the job runner into python.

### CODE REVIEW

**Comment by tautologico** [comment]
I was thinking in a similar direction: generating JUnit output from ounit2 but then processing the XML using OCaml (with ezxmlm). Using ocaml there would also make it easier to output the test code as discussed [in the issue](https://github.com/exercism/ocaml-test-runner/issues/13).

**Comment by SleeplessByte** [comment]
> That file is unfortunately XML, and parsing that in bash would have been very difficult, so this commit also rewrites the job runner into python

Just responding to this piece: this is perfectly fine. @ErikSchierboom and I have various tricks we've used across various languages just to make it able to generate the output. Some... more elegant than others. Rewriting the test runner in something that's higher level than bash to accomplish this is fine too -- in this case many of us know enough python to help if necessary.

That said: if you can process it in the language of the repo, like Andrei suggests, that's often a good idea if this track is supported (maintained) as the maintainer(s) likely know that language ;)

**Comment by tautologico** [comment]
Another point of attention is that there are some exercises with qcheck tests that won't generate the XML output. The exercise allergies is one that I've seen with qcheck tests, maybe there are others.

**Comment by georgyo** [comment]
> I was thinking in a similar direction: generating JUnit output from ounit2 but then processing the XML using OCaml (with ezxmlm). Using ocaml there would also make it easier to output the test code as discussed [in the issue](https://github.com/exercism/ocaml-test-runner/issues/13).

I should have subscribed to that issue,  there were no comments on it when I looked yesterday morning. 😆

I did debated doing it in ocaml, but I figured having the test runner be in something easily accessible to more people might be beneficial. Also my python if currently stronger than my ocaml.

If you have an implementation in progress I'm happy to close this one in favor of yours.

---

> Another point of attention is that there are some exercises with qcheck tests that won't generate the XML output. The exercise allergies is one that I've seen with qcheck tests, maybe there are others.

There is exactly one exercise, allergies, that uses qcheck, and qcheck has the ability to roll those checks into ounit.

I have some cleanup staged locally, but for that particular practice

https://github.com/exercism/ocaml/blob/8ac9ce4b06a6d782b316ccce11a89602eeab0b37/exercises/practice/allergies/test.ml#L183-L191
 would become
```
let qcheck_tests = List.map ~f:QCheck_ounit.to_ounit2_test [ prop_allergic_to_single_allergens
    ; prop_allergic_to_negative_single_allergens
    ; prop_allergic_to_multiple_allergens
    ; prop_allergies_single_allergens
    ; prop_allergies_multiple_allergens;
    ]

let _ =
  run_test_tt_main ("allergies tests" >::: (tests @ qcheck_tests))
```

**Comment by tautologico** [comment]
@georgyo I can suggest a version of the test runner written in OCaml if you think it would be useful.

**Comment by georgyo** [comment]
> @georgyo I can suggest a version of the test runner written in OCaml if you think it would be useful.

Sorry, I posted only half my reply previously. 

If you have an implementation in progress I'm happy to close this one in favor of yours.

**Comment by tautologico** [comment]
> If you have an implementation in progress I'm happy to close this one in favor of yours.

I haven't done most of the stuff in this PR, just experimented with processing the XML output with OCaml. And I was looking into parsing the test file to get the test code. I already know how to do it, but I still have to write the whole program. So most of your PR would be useful, I'd just exchange the Python file with an OCaml program.

**Review by ErikSchierboom — APPROVED** [review]
LGTM!

> I haven't done most of the stuff in this PR, just experimented with processing the XML output with OCaml. And I was looking into parsing the test file to get the test code. I already know how to do it, but I still have to write the whole program. So most of your PR would be useful, I'd just exchange the Python file with an OCaml program.

Having an OCaml program would probably best from a contributors viewpoint, as not all OCaml contributors might know Python. That said, this is perfectly fine for an initial version. Thanks a ton!

**Comment by georgyo** [comment]
Talked with @tautologico out of band, we're going to merge this as is and they will submit a new PR when the ocaml version is ready.

**Pull request merged**
